//Test Script
/*
public class SetUnionCalculator {

    public Set<Integer> calculateSetUnion(Set<Integer> set1, Set<Integer> set2) {
        Set<Integer> unionSet = new Set<Integer>();
        unionSet.addAll(set1);
        unionSet.addAll(set2);
        return unionSet;
    }
}
*/
PLACEHOLDER
public class CustomException extends Exception {}

try {
    SetUnionCalculator calculator = new SetUnionCalculator();
    
    Set<Integer> set1 = new Set<Integer>{1, 2, 3, 4};
    Set<Integer> set2 = new Set<Integer>{3, 4, 5, 6};
    Set<Integer> resultSet = calculator.calculateSetUnion(set1, set2);
    Set<Integer> expectedResult = new Set<Integer>{1, 2, 3, 4, 5, 6};
    System.assertEquals(expectedResult,resultSet);
    
} catch (Exception exc) {
    throw new CustomException('There was an error: ' + exc.getMessage());
}
