//Test Script
/*
integer total = 20;
integer total1 = total  + 5;
system.debug(total1);

integer total2 = total  - 3;
system.debug(total2);

integer total3 = total  * 4;
system.debug(total3);

integer total4 = total  / 2;
system.debug(total4);
*/

PLACEHOLDER
public class CustomException extends Exception{}
try{
   
    System.assertequals(25, total1);
    System.assertequals(17, total2);
    System.assertequals(80, total3);
    System.assertequals(10, total4);





    } catch(Exception exc){
    throw new CustomException('there is a error '+exc.getMessage());
}

