
//Test Script

/*
integer a = 35;
integer b = 26;
integer c = b;
            b = a;
            a = c;
system.debug(+ a + ',' +b);

*/
PLACEHOLDER
public class CustomException extends Exception{}
try{
   system.assertEquals(26, a);
   system.assertEquals(35,b);
} catch(Exception exc){
    throw new CustomException('there is a error'+exc.getMessage());
}
